export const designTokens = {
  colors: {
    semantic: {
      primary: {
        DEFAULT: 'var(--primary)',
        hover: 'color-mix(in oklch, var(--primary) 88%, black)',
        active: 'color-mix(in oklch, var(--primary) 80%, black)',
        foreground: 'var(--primary-foreground)',
      },
      secondary: {
        DEFAULT: 'var(--secondary)',
        hover: 'color-mix(in oklch, var(--secondary) 90%, black)',
        active: 'color-mix(in oklch, var(--secondary) 82%, black)',
        foreground: 'var(--secondary-foreground)',
      },
      accent: {
        DEFAULT: 'var(--accent)',
        hover: 'color-mix(in oklch, var(--accent) 90%, black)',
        active: 'color-mix(in oklch, var(--accent) 82%, black)',
        foreground: 'var(--accent-foreground)',
      },
      success: {
        DEFAULT: 'oklch(0.72 0.18 155)',
        hover: 'oklch(0.68 0.18 155)',
        active: 'oklch(0.64 0.18 155)',
        foreground: 'oklch(0.98 0.01 155)',
      },
      warning: {
        DEFAULT: 'oklch(0.80 0.17 82)',
        hover: 'oklch(0.76 0.17 82)',
        active: 'oklch(0.72 0.17 82)',
        foreground: 'oklch(0.16 0.02 82)',
      },
      danger: {
        DEFAULT: 'var(--destructive)',
        hover: 'color-mix(in oklch, var(--destructive) 88%, black)',
        active: 'color-mix(in oklch, var(--destructive) 80%, black)',
        foreground: 'oklch(0.99 0.01 25)',
      },
      info: {
        DEFAULT: 'oklch(0.72 0.14 242)',
        hover: 'oklch(0.68 0.14 242)',
        active: 'oklch(0.64 0.14 242)',
        foreground: 'oklch(0.98 0.01 242)',
      },
      muted: {
        DEFAULT: 'var(--muted)',
        hover: 'color-mix(in oklch, var(--muted) 92%, var(--foreground))',
        active: 'color-mix(in oklch, var(--muted) 84%, var(--foreground))',
        foreground: 'var(--muted-foreground)',
      },
      surface: {
        DEFAULT: 'var(--card)',
        strong: 'var(--popover)',
        elevated: 'color-mix(in oklch, var(--card) 84%, white)',
        foreground: 'var(--card-foreground)',
      },
      background: {
        DEFAULT: 'var(--background)',
        canvas: 'var(--canvas)',
        toolbar: 'var(--toolbar)',
        sidebar: 'var(--sidebar)',
        foreground: 'var(--foreground)',
      },
      border: {
        DEFAULT: 'var(--border)',
        subtle: 'color-mix(in oklch, var(--border) 70%, transparent)',
        strong: 'color-mix(in oklch, var(--border) 120%, var(--foreground))',
      },
      ring: {
        DEFAULT: 'var(--ring)',
        hover: 'color-mix(in oklch, var(--ring) 80%, white)',
        focus: 'color-mix(in oklch, var(--ring) 65%, white)',
      },
    },
    state: {
      hover: 'var(--hover)',
      active: 'var(--active)',
      selected: 'var(--selection)',
      focus: 'var(--focus)',
      disabled: 'var(--disabled)',
    },
  },
  typography: {
    families: {
      sans: 'var(--font-sans)',
      mono: 'var(--font-geist-mono)',
      heading: 'var(--font-heading)',
      display: 'var(--font-display)',
    },
    weights: {
      regular: 400,
      medium: 500,
      semibold: 600,
      bold: 700,
    },
    sizes: {
      displayXl: '4.5rem',
      displayLg: '3.75rem',
      displayMd: '3rem',
      heading1: '2.5rem',
      heading2: '2rem',
      heading3: '1.5rem',
      heading4: '1.25rem',
      heading5: '1.125rem',
      heading6: '1rem',
      bodyLg: '1.125rem',
      body: '1rem',
      small: '0.875rem',
      caption: '0.75rem',
      label: '0.75rem',
      code: '0.875rem',
      button: '0.875rem',
    },
    lineHeights: {
      tight: 1,
      snug: 1.2,
      normal: 1.5,
      relaxed: 1.7,
      roomy: 1.85,
    },
    letterSpacing: {
      tight: '-0.04em',
      snug: '-0.02em',
      normal: '0',
      wide: '0.02em',
      wider: '0.08em',
      widest: '0.18em',
    },
  },
  radius: {
    xs: '0.375rem',
    sm: '0.5rem',
    md: '0.75rem',
    lg: '1rem',
    xl: '1.25rem',
    '2xl': '1.5rem',
    '3xl': '1.75rem',
    '4xl': '2rem',
    full: '9999px',
  },
  shadow: {
    subtle: '0 1px 0 rgba(255, 255, 255, 0.04), 0 8px 24px rgba(0, 0, 0, 0.08)',
    premium: '0 1px 0 rgba(255, 255, 255, 0.04), 0 18px 80px rgba(0, 0, 0, 0.18)',
    elevated: '0 20px 80px rgba(0, 0, 0, 0.22)',
    glow: '0 0 0 1px color-mix(in oklch, var(--primary) 20%, transparent), 0 0 30px color-mix(in oklch, var(--primary) 24%, transparent)',
  },
  blur: {
    none: '0px',
    sm: '6px',
    md: '12px',
    lg: '16px',
    xl: '24px',
  },
  opacity: {
    disabled: 0.5,
    muted: 0.72,
    overlay: 0.84,
    veil: 0.94,
  },
  motion: {
    durations: {
      fast: 120,
      normal: 180,
      medium: 240,
      slow: 360,
      slower: 500,
    },
    easing: {
      standard: 'cubic-bezier(0.16, 1, 0.3, 1)',
      smooth: 'cubic-bezier(0.4, 0, 0.2, 1)',
      spring: 'cubic-bezier(0.22, 1, 0.36, 1)',
      snap: 'cubic-bezier(0.2, 0.8, 0.2, 1)',
    },
  },
  zIndex: {
    base: 0,
    raised: 10,
    sticky: 20,
    dropdown: 40,
    overlay: 50,
    modal: 60,
    toast: 70,
    tooltip: 80,
  },
  spacing: {
    0: '0rem',
    1: '0.25rem',
    2: '0.5rem',
    3: '0.75rem',
    4: '1rem',
    5: '1.25rem',
    6: '1.5rem',
    8: '2rem',
    10: '2.5rem',
    12: '3rem',
    14: '3.5rem',
    16: '4rem',
    20: '5rem',
    24: '6rem',
    28: '7rem',
    32: '8rem',
  },
  containers: {
    xs: '20rem',
    sm: '24rem',
    md: '28rem',
    lg: '32rem',
    xl: '36rem',
    '2xl': '42rem',
    '3xl': '48rem',
    '4xl': '56rem',
    content: '72rem',
    wide: '80rem',
    full: '100%',
  },
  breakpoints: {
    xs: '480px',
    sm: '640px',
    md: '768px',
    lg: '1024px',
    xl: '1280px',
    '2xl': '1536px',
    '3xl': '1600px',
  },
  grid: {
    columns: {
      1: 'repeat(1, minmax(0, 1fr))',
      2: 'repeat(2, minmax(0, 1fr))',
      3: 'repeat(3, minmax(0, 1fr))',
      4: 'repeat(4, minmax(0, 1fr))',
      6: 'repeat(6, minmax(0, 1fr))',
      12: 'repeat(12, minmax(0, 1fr))',
    },
    gap: {
      sm: '0.75rem',
      md: '1rem',
      lg: '1.5rem',
      xl: '2rem',
    },
  },
  icon: {
    xs: '0.625rem',
    sm: '0.75rem',
    md: '0.875rem',
    lg: '1rem',
    xl: '1.125rem',
  },
  themeModes: ['light', 'dark', 'system'] as const,
} as const;

export type DesignTokens = typeof designTokens;
export type ThemeMode = (typeof designTokens.themeModes)[number];
